CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_insert_extract_express`(
	in pdat_inicio date, 
    in pdat_final date, 
    in pnum_ano int, 
    in pnum_mes int, 
    in pnum_quinzena int, 
    in pcod_base int, 
    in pcod_entregador int,
	in pnum_extrato varchar(30), 
    in pval_verba float, 
    in pqtd_volumes int, 
    in pqtd_volumes_extra float, 
    in pval_volumes_extra float, 
    in pqtd_entregas int, 
    in pqtd_atraso int, 
	in pval_performance float, 
    in pval_producao float, 
    in pval_creditos float, 
    in pval_debitos float, 
    in pval_extravios float, 
    in pval_total_expressa float, 
    in pval_total_empresa float,
	in pcod_cliente int, 
    in pdat_credito date, 
    in pdes_unique_key varchar(30)
)
BEGIN
	insert into expressas_extrato 
		(dat_inicio, 
        dat_final, 
        num_ano, 
        num_mes, 
        num_quinzena, 
        cod_base, 
        cod_entregador,
		num_extrato, 
        val_verba, 
        qtd_volumes, 
        qtd_volumes_extra, 
        val_volumes_extra, 
        qtd_entregas, 
        qtd_atraso, 
		val_performance, 
        val_producao, 
        val_creditos, 
        val_debitos, 
        val_extravios, 
        val_total_expressa, 
        val_total_empresa,
		cod_cliente, 
        dat_credito, 
        des_unique_key )
	values 
		(pdat_inicio, 
		pdat_final, 
		pnum_ano, 
		pnum_mes, 
		pnum_quinzena, 
		pcod_base, 
		pcod_entregador,
		pnum_extrato, 
		pval_verba, 
		pqtd_volumes, 
		pqtd_volumes_extra, 
		pval_volumes_extra, 
		pqtd_entregas, 
		pqtd_atraso, 
		pval_performance, 
		pval_producao, 
		pval_creditos, 
		pval_debitos, 
		pval_extravios, 
		pval_total_expressa, 
		pval_total_empresa,
		pcod_cliente, 
		pdat_credito, 
		pdes_unique_key);
END