CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_insert_credit_worksheet_express`(
	in pcod_tipo_extrato int,
	in pcod_cadastro int,
	in pnom_cadastro varchar(70),
	in pcod_banco varchar(4),
	in pnom_banco varchar(50),
	in pdes_tipo_conta varchar(30),
	in pnum_agencia varchar(10),
	in pnum_conta varchar(30),
	in pnom_favorecido varchar(70),
	in pnum_cpf_cnpj varchar(20),
	in pval_total float,
	in pdes_unique_key varchar(30),
	in pdat_credito date,
	in pnum_extrato varchar(30),
	in pdes_forma_pagamento varchar(30),
	in pcod_modalidade_pagamento varchar(6),
	in pcod_forma_pagamento varchar(6),
	in pdom_bloqueio int,
    in pdes_observation varchar(256)
)
BEGIN
INSERT INTO bderpsisgef.financeiro_planilha_credito
	(cod_tipo_extrato, 
	cod_cadastro, 
	nom_cadastro, 
	cod_banco, 
	nom_banco, 
	des_tipo_conta, 
	num_agencia, 
	num_conta, 
	nom_favorecido, 
	num_cpf_cnpj, 
	val_total, 
	des_unique_key, 
	dat_credito, 
	num_extrato, 
	des_forma_pagamento, 
	cod_modalidade_pagamento, 
	cod_forma_pagamento, 
    dom_bloqueio,
    des_observation)
	VALUES
	(pcod_tipo_extrato, 
	pcod_cadastro, 
	pnom_cadastro, 
	pcod_banco, 
	pnom_banco, 
	pdes_tipo_conta, 
	pnum_agencia, 
	pnum_conta, 
	pnom_favorecido, 
	pnum_cpf_cnpj, 
	pval_total, 
	pdes_unique_key, 
	pdat_credito, 
	pnum_extrato, 
	pdes_forma_pagamento, 
	pcod_modalidade_pagamento,
	pcod_forma_pagamento, 
    pdom_bloqueio,
    pdes_observation);
END