CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_update_extract_express`(
	in pid_extrato int, 
	in pdat_inicio date, 
    in pdat_final date, 
    in pnum_ano int, 
    in pnum_mes int, 
    in pnum_quinzena int, 
    in pcod_base int, 
    in pcod_entregador int,
	in pnum_extrato varchar(30), 
    in pval_verba float, 
    in pqtd_volumes int, 
    in pqtd_volumes_extra float, 
    in pval_volumes_extra float, 
    in pqtd_entregas int, 
    in pqtd_atraso int, 
	in pval_performance float, 
    in pval_producao float, 
    in pval_creditos float, 
    in pval_debitos float, 
    in pval_extravios float, 
    in pval_total_expressa float, 
    in pval_total_empresa float,
	in pcod_cliente int, 
    in pdat_credito date, 
    in pdes_unique_key varchar(30)
)
BEGIN
	update expressas_extrato 
    set
        dat_inicio = pdat_inicio, 
        dat_final = pdat_final, 
        num_ano = pnum_ano, 
        num_mes = pnum_mes, 
        num_quinzena = pnum_quinzena, 
        cod_base = pcod_base, 
        cod_entregador = pcod_entregador,
		num_extrato = pnum_extrato, 
        val_verba = pval_verba, 
        qtd_volumes = pqtd_volumes, 
        qtd_volumes_extra = pqtd_volumes_extra, 
        val_volumes_extra = pval_volumes_extra, 
        qtd_entregas = pqtd_entregas, 
        qtd_atraso = pqtd_atraso, 
		val_performance = pval_performance, 
        val_producao = pval_producao, 
        val_creditos = pval_creditos, 
        val_debitos = pval_debitos, 
        val_extravios = pval_extravios, 
        val_total_expressa = pval_total_expressa, 
        val_total_empresa = pval_total_empresa,
		cod_cliente = pcod_cliente, 
        dat_credito = pdat_credito, 
        des_unique_key = pdes_unique_key
	where id_extrato = pid_extrato;
END